//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SDAM
{
    using System;
    using System.Collections.Generic;
    
    public partial class BALL
    {
        public int IDBALL { get; set; }
        public int IDDISS { get; set; }
        public int IDSUDENT { get; set; }
        public int BALL1 { get; set; }
    
        public virtual DISS DISS { get; set; }
        public virtual SUDENT SUDENT { get; set; }
    }
}
