//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SDAM
{
    using System;
    using System.Collections.Generic;
    
    public partial class DISS
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public DISS()
        {
            this.BALL = new HashSet<BALL>();
        }
    
        public int IDDISS { get; set; }
        public string NAME { get; set; }
        public string PREPOD { get; set; }
        public string SEMESTOR { get; set; }
        public int GOD { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<BALL> BALL { get; set; }
    }
}
