//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SDAM
{
    using System;
    using System.Collections.Generic;
    
    public partial class SUDENT
    {
        public int IDSTUDENT { get; set; }
        public string LASTNAME { get; set; }
        public string NAME { get; set; }
        public int IDGRUP { get; set; }
    }
}
